baseURL = "https://twentynineteen-hugo-demo.netlify.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "twentynineteen-hugo"

# Syntax highlighting
pygmentsUseClasses=true
pygmentsCodefences=true

# Pagination
paginate = 5

# Output formats (for search index)
[outputs]
Home = ["HTML", "RSS", "JSON"]

# Site params
[params]
privacy_link = "/privacy/"
description = "TwentyNineteen ported from WordPress"

# Social menu
[menu]
  [[menu.social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/jeremybise/twentynineteen-hugo"
  [[menu.social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/gohugoio"